server {
    listen 80;
    server_name localhost;

    root /var/www/frontend/dist;
    index index.html;

    location = /api {
        return 301 /api/health;
    }

    location ^~ /api/ {
        include fastcgi_params;
        fastcgi_pass php:9000;
        fastcgi_param SCRIPT_FILENAME /var/www/backend/public/index.php;
        fastcgi_param SCRIPT_NAME /index.php;
        fastcgi_param DOCUMENT_ROOT /var/www/backend/public;
        fastcgi_param QUERY_STRING $query_string;
        fastcgi_param REQUEST_URI $request_uri;
        fastcgi_param PATH_INFO $uri;
    }

    location = /favicon.ico {
        log_not_found off;
        access_log off;
        try_files /favicon.ico =204;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}